### ISSUE TITLE
Permission denied: '/sys/class/rtc/rtc0/wakealarm'

### ISSUE THREAD

**Issue by hewfish** [ThomasVon2021/pikvm-CM4-Board#19]
I'm seeing a repeating error in the log PiKVM web log that seems linked to the RTC module. I'm running the latest v3 hat image of PiKVM

> PermissionError: [Errno 13] Permission denied: '/sys/class/rtc/rtc0/wakealarm'

Full error log:

[2022-03-16 00:25:07 kvmd-watchdog.service] --- kvmd.apps.watchdog                INFO --- Running watchdog loop on RTC0 ...
[2022-03-16 00:25:07 kvmd-watchdog.service] --- Traceback (most recent call last):
[2022-03-16 00:25:07 kvmd-watchdog.service] ---   File "/usr/bin/kvmd-watchdog", line 9, in <module>
[2022-03-16 00:25:07 kvmd-watchdog.service] ---     main()
[2022-03-16 00:25:07 kvmd-watchdog.service] ---   File "/usr/lib/python3.10/site-packages/kvmd/apps/watchdog/__init__.py", line 119, in main
[2022-03-16 00:25:07 kvmd-watchdog.service] ---     options.cmd(config.watchdog)
[2022-03-16 00:25:07 kvmd-watchdog.service] ---   File "/usr/lib/python3.10/site-packages/kvmd/apps/watchdog/__init__.py", line 80, in _cmd_run
[2022-03-16 00:25:07 kvmd-watchdog.service] ---     _reset_alarm(config.rtc, config.timeout)
[2022-03-16 00:25:07 kvmd-watchdog.service] ---   File "/usr/lib/python3.10/site-packages/kvmd/apps/watchdog/__init__.py", line 65, in _reset_alarm
[2022-03-16 00:25:07 kvmd-watchdog.service] ---     _write_int(rtc, "wakealarm", wake)
[2022-03-16 00:25:07 kvmd-watchdog.service] ---   File "/usr/lib/python3.10/site-packages/kvmd/apps/watchdog/__init__.py", line 55, in _write_int
[2022-03-16 00:25:07 kvmd-watchdog.service] ---     with open(_join_rtc(rtc, key), "w") as value_file:
[2022-03-16 00:25:07 kvmd-watchdog.service] --- PermissionError: [Errno 13] Permission denied: '/sys/class/rtc/rtc0/wakealarm'

**Comment by hzzfly** [comment]
did you try this https://github.com/ThomasVon2021/pikvm-CM4-Board#25real-time-clock-rtc

**Comment by hewfish** [comment]
Yes, the rtc is loaded and available, however there is not wakealarm under
that class

Thanks

**Comment by hewfish** [comment]
As per my previous commend:

```
[root@pikvm boot]# cat config.txt 
# See /boot/overlays/README for all available options
initramfs initramfs-linux.img followkernel

hdmi_force_hotplug=1
gpu_mem=128
enable_uart=1
dtoverlay=tc358743
dtoverlay=disable-bt
dtoverlay=dwc2,dr_mode=peripheral
#dtparam=act_led_gpio=13

# HDMI audio capture
dtoverlay=tc358743-audio

# SPI (AUM)
dtoverlay=spi0-1cs

# I2C (display)
dtparam=i2c_arm=on

# Clock
#dtoverlay=i2c-rtc,pcf8563
dtoverlay=i2c-rtc,ds1307
```

```
[kvmd-webterm@pikvm rtc0]$ ls
device  subsystem  dev      max_user_freq  since_epoch  uevent
power   date       hctosys  name           time
[kvmd-webterm@pikvm rtc0]$ pwd
/sys/class/rtc/rtc0
[kvmd-webterm@pikvm rtc0]$ 

```

There is clearly no wakealarm under that tree. Any ideas?

**Comment by nmaster2042** [comment]
Same issue here.

How to solve this ?

**Comment by Martin-HiPi** [comment]
That's what happens when your software is meant for PiKVM v3 but used on BliKVM...

The PiKVM v3 team #wontfix since it's not their problem!

**Comment by DerTFL** [comment]
You can completely disable `kvmd-watchdog` by 
```
rw
systemctl disable --now kvmd-watchdog
ro
```

**Comment by hewfish** [comment]
Disabling the specific wakealarm service seems to remove the log issue,
does it have any other detrimental effect?

**Comment by nmaster2042** [comment]
I think it only remove the ability to power on the rpi at a define hour.
To be checked and confirmed.

**Comment by hewfish** [comment]
I don't think the ds1307 chip supports that function anyway, hence why
there is no wakealarm function exposed and available.
